### ISSUE TITLE
how to build

### ISSUE THREAD

**Issue by peterpavles** [WKL-Sec/HiddenDesktop#2]
which development environment can be used to build the executables. i tried kali but they throw errors when building with following commandline

make -f Makefile

before that i install mingw using

apt-get install mingw-w64 -y

but make commands throws errors array out of bound

**Comment by nurfed1** [comment]
If you are talking about these errors: 
`In function ‘__readgsqword’,
    inlined from ‘NtCurrentTeb’ at /usr/x86_64-w64-mingw32/include/winnt.h:9094:73,
    inlined from ‘BofMain’ at client/bfmain.c:48:39:
/usr/x86_64-w64-mingw32/include/psdk_inc/intrin-impl.h:838:1: error: array subscript 0 is outside array bounds of ‘long long unsigned int[0]’ [-Werror=array-bounds]
  838 | __buildreadseg(__readgsqword, unsigned __int64, "gs", "q")
`

There seems to be a bug in mingw gcc version 12, downgrading to mingw gcc 11 fixed that for me.

**Comment by luxcupitor** [comment]
You can try adding `-Wno-array-bounds` to the compiler flags as well, but no idea if that causes any instability. YMMV.
Looks like it will be needed in 2 places in the Makefile:
```
SCFLAGS     := $(SCFLAGS) -falign-labels=1 -fPIC -fno-exceptions -Wall -Werror -Wno-array-bounds
BFFLAGS     := $(BFFLAGS) -Os -s -Qn -nostdlib -Werror -Wall -Wno-array-bounds
```

**Comment by kyleavery** [comment]
I'm using MinGW 9.3 on Windows. You also need NASM, Python3, and the pefile Pip package.

**Comment by peterpavles** [comment]
> If you are talking about these errors: `In function ‘__readgsqword’, inlined from ‘NtCurrentTeb’ at /usr/x86_64-w64-mingw32/include/winnt.h:9094:73, inlined from ‘BofMain’ at client/bfmain.c:48:39: /usr/x86_64-w64-mingw32/include/psdk_inc/intrin-impl.h:838:1: error: array subscript 0 is outside array bounds of ‘long long unsigned int[0]’ [-Werror=array-bounds] 838 | __buildreadseg(__readgsqword, unsigned __int64, "gs", "q") `
> 
> There seems to be a bug in mingw gcc version 12, downgrading to mingw gcc 11 fixed that for me.

could you help how can i install mingw 11 version on kali.

can't seem to find any help about downgrading mingw 12 or install mingw 11
