### ISSUE TITLE
windows 11 and tasks?

### ISSUE THREAD

**Issue by axel9546** [WKL-Sec/HiddenDesktop#5]
Hi there,
I'd like to ask, if the software can work between two normal machines, in this case, a windows 10 pc, and another windows 10 pc.

Also, it would be awesome to make a step by step process for anyone who intend to use the software, for example listing any other software with the installation guide and configuration.
Since the video has started after the configuration has done, someone like me, unfortunately doesn't know how to procede.

It would awesome to have a step by step process

Thanks! :)

**Comment by kyleavery** [comment]
Yes it will work
